import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'solucao/index',
      label: 'Solução',
    },

    {
      type: 'category',
      label: 'Sprint 1',
      link: {type: 'doc', id: 'sprint-1/index'},
      items: [
        {type: 'autogenerated', dirName: 'sprint-1'},
      ],
    },
    {
      type: 'category',
      label: 'Sprint 2',
      link: {type: 'doc', id: 'sprint-2/index'},
      items: [
        {type: 'autogenerated', dirName: 'sprint-2'},
      ],
    },
    {
      type: 'category',
      label: 'Sprint 3',
      link: {type: 'doc', id: 'sprint-3/index'},
      items: [
        {type: 'autogenerated', dirName: 'sprint-3'},
      ],
    },
    {
      type: 'category',
      label: 'Sprint 4',
      link: {type: 'doc', id: 'sprint-4/index'},
      items: [
        {type: 'autogenerated', dirName: 'sprint-4'},
      ],
    },
    {
      type: 'category',
      label: 'Sprint 5',
      link: {type: 'doc', id: 'sprint-5/index'},
      items: [
        {type: 'autogenerated', dirName: 'sprint-5'},
      ],
    },
  ],
};

export default sidebars;
